server:
   port: 9090

spring:
   application:
      name: API-GATEWAY
   config:
      import: configserver:http://localhost:9296
   cloud:
      gateway:
         routes:
            - 
               id: ORDER-SERVICE
               uri: lb://ORDER-SERVICE
               predicates:
                  - Path=/orders/**
               filters:
                  - AuthenticationFilter
            - 
               id: PAYMENT-SERVICE
               uri: lb://PAYMENT-SERVICE
               predicates:
                  - Path=/payments/**
            - 
               id: PRODUCT-SERVICE
               uri: lb://PRODUCT-SERVICE
               predicates:
                  - Path=/inventory/**
               filters:
                  - AuthenticationFilter
            -
               id: SECURITY-SERVICE
               uri: lb://SECURITY-SERVICE
               predicates:
                  - Path=/auth/**
