server:
  port: 8080

spring:
  application:
    name: CUSTOMER-SERVICE
  datasource:
    hikari:
      maximum-pool-size: 20
    url: jdbc:mysql://${SPRING_DATASOURCE_HOST}:3306/qs-customers?createDatabaseIfNotExist=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      generate-ddl: true
      ddl-auto: create
      format_sql: false