server:
   port: 8082

spring:
   application:
      name: PAYMENT-SERVICE
   config:
      import: configserver:http://localhost:9296
   datasource:
      url: jdbc:mysql://localhost:3306/learn-microservices?createDatabaseIfNotExist=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
   jpa:
      show-sql: true
      hibernate:
         generate-ddl: true
         ddl-auto: create
         format_sql: true