server:
  port: 9080

spring:
  application:
    name: SECURITY-SERVICE
  config:
    import: configserver:http://localhost:9296
  datasource:
    url: jdbc:mysql://localhost:3306/quick-shop
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      generate-ddl: true
      ddl-auto: update
      format_sql: true