server:
   port: 8081

logging:
   level:
      com:
         microservices:
            order:
               service:
                  connectors: debug

spring:
   application:
      name: ORDER-SERVICE
   config:
      import:
         - configserver:http://localhost:9296
#         - vault://
   datasource:
      url: jdbc:mysql://localhost:3306/quick-shop?createDatabaseIfNotExist=true
      username: ${database.username}
      password: ${database.password}
      driver-class-name: com.mysql.cj.jdbc.Driver
   jpa:
      show-sql: true
      hibernate:
         ddl-auto: create
         format_sql: true
   cloud:
      vault:
         kv:
            enabled: true
         authentication: TOKEN
         token: ${vault.token}
         scheme: http
         host: 127.0.0.1
         port: 8200


management:
   health:
      circuitbreakers:
         enabled: true
   endpoints:
      web:
         exposure:
            include: '*'
   endpoint:
      health:
         show-details: always
   tracing:
      sampling:
         probability: 1.0

#resilience4j:
#   circuitbreaker:
#      configs:
#         default:
#            registerHealthIndicator: true
#            slidingWindowSize: 10
#            slidingWindowType: COUNT_BASED
#            minimumNumberOfCalls: 5
#            permittedNumberOfCallsInHalfOpenState: 2
#            automaticTransitionFromOpenToHalfOpenEnabled: true
#            waitDurationInOpenState: 5s
#            failureRateThreshold: 50
#      instances:
#         placeOrders:
#            baseConfig: default
#   retry:
#      instances:
#         retryPlaceOrders:
#            registerHealthIndicator: true
#            maxRetryAttempts: 5
#            waitDuration: 3s


