qs:
  web:
    security:
      method-security:
        enabled: false
      config:
        interceptor:
          enabled: false
  core:
    togglz:
      feature-togglz-service-uri: http://localhost:8888//api/feature-togglz-service/togglz
      enable-in-memory-togglz-as-fallback: false
      enable-custom-activation-strategy: false


