server:
   port: 8080
#   compression:
#      enabled: true
#      mime-types: application/json,application/xml,text/html,text/xml,text/plain
#      min-response-size: 1024

spring:
   application:
      name: PRODUCT-SERVICE
   config:
      import: optional:configserver:http://localhost:9296
   datasource:
      hikari:
         maximum-pool-size: 20
      url: jdbc:mysql://localhost:3306/quick-shop?createDatabaseIfNotExist=true
      username: root
      password: admin
      driver-class-name: com.mysql.cj.jdbc.Driver
   jpa:
      open-in-view: false
      show-sql: true
      hibernate:
         generate-ddl: true
         ddl-auto: create
         format_sql: false

management:
   security:
      enabled: false
   tracing:
      sampling:
         probability: 1.0

resilience4j:
   ratelimiter:
      instances:
         getProducts:
            limitForPeriod: 2 # 2 requests allowed every 4s with a timeout duration of 3s per request
            limitRefreshPeriod: 4s
            timeoutDuration: 3s

logging:
   level:
      org.springframework.orm.jpa.JpaTransactionManager: ERROR
      org.springframework.jdbc.datasource.DataSourceUtils: ERROR
      org.springframework.transaction.interceptor.TransactionInterceptor: ERROR
      org.springframework.cache: TRACE